### ISSUE TITLE
ubRacing function error

### ISSUE THREAD

**Issue by nathnx** [dalpozz/unbalanced#2]
`
library(unbalanced)
data(ubIonosphere)
set.seed(1234)
ubConf <- list(percOver=250, percUnder=150, k=3, perc=50, method="percPos", w=NULL)
results <- ubRacing(Class ~., ubIonosphere, "randomForest", positive=1, metric="auc", ubConf=ubConf, ntree=10)
`

**Error in predCandidate(Xtr, Ytr, Xts, Yts, algo, balanceTypes[j], positive,  :  task 6 failed - "level sets of factors are different"**

**Comment by dalpozz** [comment]
should be fixed now, please reinstall the version on github
